package ndhiep.entities;
// Generated May 30, 2018 1:49:39 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "albumwebspring")
public class Album implements java.io.Serializable {

	private Integer id;
	private String nameAlbum;
	private String kind;

	public Album() {
	}

	public Album(String nameAlbum, String kind) {
		this.nameAlbum = nameAlbum;
		this.kind = kind;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nameAlbum", nullable = false)
	public String getNameAlbum() {
		return this.nameAlbum;
	}

	public void setNameAlbum(String nameAlbum) {
		this.nameAlbum = nameAlbum;
	}

	@Column(name = "kind", nullable = false, length = 45)
	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

}
